//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

import java.util.List;

import org.jboss.ejb3.metadata.spi.javaee.DescriptionMetaData;
import org.jboss.ejb3.metadata.spi.javaee.IdMetaData;
import org.jboss.ejb3.metadata.spi.javaee.InjectionTargetMetaData;

/**
 * 
 * 
 *             The annotationType is used to add annotations to a bean class,
 *             method, or field.
 * 
 *          
 * 
 * <p>Java class for annotationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="annotationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://java.sun.com/xml/ns/javaee}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="annotation-class" type="{http://www.jboss.com/xml/ns/javaee}annotation-classType"/>
 *         &lt;element name="annotation-implementation-class" type="{http://www.jboss.com/xml/ns/javaee}annotation-classType"/>
 *         &lt;element name="injection-target" type="{http://www.jboss.com/xml/ns/javaee}injection-targetType" minOccurs="0"/>
 *         &lt;element name="property" type="{http://www.jboss.com/xml/ns/javaee}annotation-propertyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface AnnotationMetaData extends IdMetaData
{

   /**
    * Gets the value of the description property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the description property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getDescription().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link DescriptionMetaData }
    * 
    * 
    */
   List<DescriptionMetaData> getDescription();

   /**
    * @return Returns the fully qualified class name of the annotation
    *     
    */
   String getAnnotationClass();

   /**
    * Sets the fully qualified class name of the annotation to be added
    * to the bean
    * 
    * @param annotationClassName Fully qualified class name of the annotation
    *     
    */
   void setAnnotationClass(String annotationClassName);

   /**
    * @return Returns the fully qualified classname of the annotation implementation
    * class
    *     
    */
   String getAnnotationImplementationClass();

   /**
    * Sets the fully qualified class name of the annotation implementation
    * class
    * 
    * @param annotationImplClassName Fully qualified class name of the annotation
    *                   implementation.
    *     
    */
   void setAnnotationImplementationClass(String annotationImplClassName);

   /**
    * @return Returns the injection target
    *     
    */
   InjectionTargetMetaData getInjectionTarget();

   /**
    * Sets the injection target for this annotation
    * 
    * @param injectionTarget
    *     
    */
   void setInjectionTarget(InjectionTargetMetaData injectionTarget);

   /**
    * Returns the properties associated with this annotation metadata
    * 
    * 
    */
   List<AnnotationPropertyMetaData> getProperties();
   
   /**
    * Sets the annotation properties of this annotation
    * @param annotationProperties
    */
   void setProperties(List<AnnotationPropertyMetaData> annotationProperties);

}
