//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

import java.util.List;

import org.jboss.ejb3.metadata.spi.javaee.DescriptionMetaData;

/**
 *  The cluster-config element allows to specify cluster specific settings.
 *          
 * 
 * <p>Java class for cluster-configType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cluster-configType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://java.sun.com/xml/ns/javaee}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="partition-name" type="{http://www.jboss.com/xml/ns/javaee}partition-nameType" minOccurs="0"/>
 *         &lt;element name="home-load-balance-policy" type="{http://www.jboss.com/xml/ns/javaee}load-balance-policyType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="bean-load-balance-policy" type="{http://www.jboss.com/xml/ns/javaee}bean-load-balance-policyType" minOccurs="0"/>
 *           &lt;element name="load-balance-policy" type="{http://www.jboss.com/xml/ns/javaee}load-balance-policyType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="session-state-manager-jndi-name" type="{http://java.sun.com/xml/ns/javaee}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface ClusterConfigMetaData
{

   /**
    * Gets the value of the description property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the description property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getDescription().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link DescriptionMetaData }
    * 
    * 
    */
   List<DescriptionMetaData> getDescription();

   /**
    * Gets the value of the partitionName property.
    * 
    * @return
    *     possible object is
    *     {@link PartitionNameType }
    *     
    */
   String getPartitionName();

   /**
    * Sets the value of the partitionName property.
    * 
    * @param value
    *     allowed object is
    *     {@link PartitionNameType }
    *     
    */
   void setPartitionName(String value);

   /**
    * Gets the value of the homeLoadBalancePolicy property.
    * 
    * @return
    *     possible object is
    *     {@link LoadBalancePolicyType }
    *     
    */
   String getHomeLoadBalancePolicy();

   /**
    * Sets the value of the homeLoadBalancePolicy property.
    * 
    * @param value
    *     allowed object is
    *     {@link LoadBalancePolicyType }
    *     
    */
   void setHomeLoadBalancePolicy(String value);

   /**
    * Gets the value of the beanLoadBalancePolicy property.
    * 
    * @return
    *     possible object is
    *     {@link BeanLoadBalancePolicyType }
    *     
    */
   String getBeanLoadBalancePolicy();

   /**
    * Sets the value of the beanLoadBalancePolicy property.
    * 
    * @param value
    *     allowed object is
    *     {@link BeanLoadBalancePolicyType }
    *     
    */
   void setBeanLoadBalancePolicy(String value);

   /**
    * Gets the value of the loadBalancePolicy property.
    * 
    * @return
    *     possible object is
    *     {@link LoadBalancePolicyType }
    *     
    */
   String getLoadBalancePolicy();

   /**
    * Sets the value of the loadBalancePolicy property.
    * 
    * @param value
    *     allowed object is
    *     {@link LoadBalancePolicyType }
    *     
    */
   void setLoadBalancePolicy(String value);

   /**
    * Gets the value of the sessionStateManagerJndiName property.
    * 
    * @return
    *     possible object is
    *     {@link com.sun.java.xml.ns.javaee.String }
    *     
    */
   String getSessionStateManagerJndiName();

   /**
    * Sets the value of the sessionStateManagerJndiName property.
    * 
    * @param value
    *     allowed object is
    *     {@link com.sun.java.xml.ns.javaee.String }
    *     
    */
   void setSessionStateManagerJndiName(String value);

   /**
    * Gets the value of the id property.
    * 
    * @return
    *     possible object is
    *     {@link java.lang.String }
    *     
    */
   java.lang.String getId();

   /**
    * Sets the value of the id property.
    * 
    * @param value
    *     allowed object is
    *     {@link java.lang.String }
    *     
    */
   void setId(java.lang.String value);

}
