//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.06.08 at 07:12:16 PM IST
//

package org.jboss.ejb3.metadata.spi.jboss;

import org.jboss.ejb3.metadata.spi.javaee.ResourceRefMetaData;

/**
 *  The resource-ref element gives a mapping between the "code name" of a
 *             resource (res-ref-name, provided by the Bean Developer) and its "xml name" (resource-name,
 *             provided by the Application Assembler). If no resource-ref is provided, jboss will assume
 *             that "xml-name" = "code name" See resource-managers.
 *
 * <p>Java class for resource-refType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="resource-refType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://java.sun.com/xml/ns/javaee}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="res-ref-name" type="{http://java.sun.com/xml/ns/javaee}jndi-nameType" minOccurs="0"/>
 *         &lt;element name="res-type" type="{http://java.sun.com/xml/ns/javaee}fully-qualified-classType" minOccurs="0"/>
 *         &lt;element name="res-auth" type="{http://java.sun.com/xml/ns/javaee}res-authType" minOccurs="0"/>
 *         &lt;element name="res-sharing-scope" type="{http://java.sun.com/xml/ns/javaee}res-sharing-scopeType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="resource-name" type="{http://java.sun.com/xml/ns/javaee}xsdStringType"/>
 *           &lt;element name="jndi-name" type="{http://java.sun.com/xml/ns/javaee}xsdStringType"/>
 *           &lt;element name="mapped-name" type="{http://java.sun.com/xml/ns/javaee}xsdStringType"/>
 *           &lt;element name="res-url" type="{http://java.sun.com/xml/ns/javaee}xsdStringType"/>
 *         &lt;/choice>
 *         &lt;element name="injection-target" type="{http://www.jboss.com/xml/ns/javaee}injection-targetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ignore-dependency" type="{http://java.sun.com/xml/ns/javaee}emptyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
public interface JBossResourceRefMetaData extends ResourceRefMetaData
{

   /**
    * Gets the value of the resourceName property.
    *
    * @return
    *     possible object is
    *     {@link XsdStringType }
    *
    */
   String getResourceName();

   /**
    * Sets the value of the resourceName property.
    *
    * @param value
    *     allowed object is
    *     {@link XsdStringType }
    *
    */
   void setResourceName(String value);

   /**
    * Gets the value of the jndiName property.
    *
    * @return
    *     possible object is
    *     {@link XsdStringType }
    *
    */
   String getJndiName();

   /**
    * Sets the value of the jndiName property.
    *
    * @param value
    *     allowed object is
    *     {@link XsdStringType }
    *
    */
   void setJndiName(String value);

   /**
    * Gets the value of the resUrl property.
    *
    * @return
    *     possible object is
    *     {@link XsdStringType }
    *
    */
   String getResUrl();

   /**
    * Sets the value of the resUrl property.
    *
    * @param value
    *     allowed object is
    *     {@link XsdStringType }
    *
    */
   void setResUrl(String value);

   /**
    * Gets the value of the ignoreDependency property.
    *
    * @return
    *     possible object is
    *     {@link EmptyType }
    *
    */
   boolean isIgnoreDependency();

   /**
    * Sets the value of the ignoreDependency property.
    *
    * @param value
    *     allowed object is
    *     {@link EmptyType }
    *
    */
   void setIgnoreDependency(boolean value);

}
