//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

import java.util.List;

import org.jboss.ejb3.metadata.spi.javaee.SessionBeanMetaData;

/**
 *  The session element holds information specific to jboss and not declared
 *             in ejb-jar.xml about a session bean, such as jndi name, container configuration, and
 *             resource managers. (see tags for details) The bean should already be declared in
 *             ejb-jar.xml, with the same ejb-name. Used in: enterprise-beans 
 * 
 * <p>Java class for session-beanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="session-beanType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.jboss.com/xml/ns/javaee}descriptionGroup"/>
 *         &lt;element name="ejb-name" type="{http://java.sun.com/xml/ns/javaee}ejb-nameType"/>
 *         &lt;element name="mapped-name" type="{http://java.sun.com/xml/ns/javaee}xsdStringType" minOccurs="0"/>
 *         &lt;group ref="{http://www.jboss.com/xml/ns/javaee}jndiEnvironmentRefsGroup"/>
 *         &lt;element name="security-identity" type="{http://www.jboss.com/xml/ns/javaee}security-identityType" minOccurs="0"/>
 *         &lt;element name="local-binding" type="{http://www.jboss.com/xml/ns/javaee}local-bindingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="remote-binding" type="{http://www.jboss.com/xml/ns/javaee}remote-bindingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="business-local" type="{http://java.sun.com/xml/ns/javaee}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="business-remote" type="{http://java.sun.com/xml/ns/javaee}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="jndi-name" type="{http://java.sun.com/xml/ns/javaee}jndi-nameType" minOccurs="0"/>
 *         &lt;element name="home-jndi-name" type="{http://java.sun.com/xml/ns/javaee}jndi-nameType" minOccurs="0"/>
 *         &lt;element name="local-jndi-name" type="{http://www.jboss.com/xml/ns/javaee}local-jndi-nameType" minOccurs="0"/>
 *         &lt;element name="local-home-jndi-name" type="{http://java.sun.com/xml/ns/javaee}jndi-nameType" minOccurs="0"/>
 *         &lt;element name="jndi-binding-policy" type="{http://www.jboss.com/xml/ns/javaee}jndi-binding-policyType" minOccurs="0"/>
 *         &lt;element name="clustered" type="{http://www.jboss.com/xml/ns/javaee}clusteredType" minOccurs="0"/>
 *         &lt;element name="cluster-config" type="{http://www.jboss.com/xml/ns/javaee}cluster-configType" minOccurs="0"/>
 *         &lt;element name="security-domain" type="{http://www.jboss.com/xml/ns/javaee}security-domainType" minOccurs="0"/>
 *         &lt;element name="method-attributes" type="{http://www.jboss.com/xml/ns/javaee}method-attributesType" minOccurs="0"/>
 *         &lt;element name="depends" type="{http://www.jboss.com/xml/ns/javaee}dependsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="annotation" type="{http://www.jboss.com/xml/ns/javaee}annotationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ignore-dependency" type="{http://www.jboss.com/xml/ns/javaee}ignore-dependencyType" minOccurs="0"/>
 *         &lt;element name="aop-domain-name" type="{http://www.jboss.com/xml/ns/javaee}aop-domain-nameType" minOccurs="0"/>
 *         &lt;element name="cache-config" type="{http://www.jboss.com/xml/ns/javaee}cache-configType" minOccurs="0"/>
 *         &lt;element name="pool-config" type="{http://www.jboss.com/xml/ns/javaee}pool-configType" minOccurs="0"/>
 *         &lt;element name="concurrent" type="{http://www.jboss.com/xml/ns/javaee}concurrentType" minOccurs="0"/>
 *         &lt;element name="jndi-ref" type="{http://www.jboss.com/xml/ns/javaee}jndi-refType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="port-component" type="{http://www.jboss.com/xml/ns/javaee}port-componentType" minOccurs="0"/>
 *         &lt;element name="ejb-timeout-identity" type="{http://www.jboss.com/xml/ns/javaee}security-identityType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface JBossSessionBeanMetaData extends SessionBeanMetaData
{

   List<JBossMessageDestinationRefMetaData> getMessageDestinationRef();

   /**
    * Gets the value of the localBinding property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the localBinding property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getLocalBinding().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link LocalBindingMetaData }
    * 
    * 
    */
   List<LocalBindingMetaData> getLocalBinding();

   /**
    * Gets the value of the remoteBinding property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the remoteBinding property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getRemoteBinding().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link RemoteBindingMetaData }
    * 
    * 
    */
   List<RemoteBindingMetaData> getRemoteBinding();

   /**
    * Gets the value of the jndiName property.
    * 
    * @return
    *     possible object is
    *     {@link JndiNameType }
    *     
    */
   String getJndiName();

   /**
    * Sets the value of the jndiName property.
    * 
    * @param value
    *     allowed object is
    *     {@link JndiNameType }
    *     
    */
   void setJndiName(String value);

   /**
    * Gets the value of the homeJndiName property.
    * 
    * @return
    *     possible object is
    *     {@link JndiNameType }
    *     
    */
   String getHomeJndiName();

   /**
    * Sets the value of the homeJndiName property.
    * 
    * @param value
    *     allowed object is
    *     {@link JndiNameType }
    *     
    */
   void setHomeJndiName(String value);

   /**
    * Gets the value of the localJndiName property.
    * 
    * @return
    *     possible object is
    *     {@link LocalJndiNameType }
    *     
    */
   String getLocalJndiName();

   /**
    * Sets the value of the localJndiName property.
    * 
    * @param value
    *     allowed object is
    *     {@link LocalJndiNameType }
    *     
    */
   void setLocalJndiName(String value);

   /**
    * Gets the value of the localHomeJndiName property.
    * 
    * @return
    *     possible object is
    *     {@link JndiNameType }
    *     
    */
   String getLocalHomeJndiName();

   /**
    * Sets the value of the localHomeJndiName property.
    * 
    * @param value
    *     allowed object is
    *     {@link JndiNameType }
    *     
    */
   void setLocalHomeJndiName(String value);

   /**
    * Gets the value of the jndiBindingPolicy property.
    * 
    * @return
    *     possible object is
    *     {@link JndiBindingPolicyType }
    *     
    */
   String getJndiBindingPolicy();

   /**
    * Sets the value of the jndiBindingPolicy property.
    * 
    * @param value
    *     allowed object is
    *     {@link JndiBindingPolicyType }
    *     
    */
   void setJndiBindingPolicy(String value);

   /**
    * Gets the value of the clustered property.
    * 
    * @return
    *     possible object is
    *     {@link ClusteredType }
    *     
    */
   boolean getClustered();

   /**
    * Sets the value of the clustered property.
    * 
    * @param value
    *     allowed object is
    *     {@link ClusteredType }
    *     
    */
   void setClustered(boolean value);

   /**
    * Gets the value of the clusterConfig property.
    * 
    * @return
    *     possible object is
    *     {@link ClusterConfigMetaData }
    *     
    */
   ClusterConfigMetaData getClusterConfig();

   /**
    * Sets the value of the clusterConfig property.
    * 
    * @param value
    *     allowed object is
    *     {@link ClusterConfigMetaData }
    *     
    */
   void setClusterConfig(ClusterConfigMetaData value);

   /**
    * Gets the value of the securityDomain property.
    * 
    * @return
    *     possible object is
    *     {@link SecurityDomainType }
    *     
    */
   String getSecurityDomain();

   /**
    * Sets the value of the securityDomain property.
    * 
    * @param value
    *     allowed object is
    *     {@link SecurityDomainType }
    *     
    */
   void setSecurityDomain(String value);

   /**
    * Gets the value of the methodAttributes property.
    * 
    * @return
    *     possible object is
    *     {@link MethodAttributesMetaData }
    *     
    */
   MethodAttributesMetaData getMethodAttributes();

   /**
    * Sets the value of the methodAttributes property.
    * 
    * @param value
    *     allowed object is
    *     {@link MethodAttributesMetaData }
    *     
    */
   void setMethodAttributes(MethodAttributesMetaData value);

   /**
    * Gets the value of the depends property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the depends property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getDepends().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link DependsType }
    * 
    * 
    */
   List<String> getDepends();

   /**
    * Gets the value of the annotation property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the annotation property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getAnnotation().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link AnnotationMetaData }
    * 
    * 
    */
   List<AnnotationMetaData> getAnnotation();

   /**
    * Gets the value of the ignoreDependency property.
    * 
    * @return
    *     possible object is
    *     {@link IgnoreDependencyMetaData }
    *     
    */
   IgnoreDependencyMetaData getIgnoreDependency();

   /**
    * Sets the value of the ignoreDependency property.
    * 
    * @param value
    *     allowed object is
    *     {@link IgnoreDependencyMetaData }
    *     
    */
   void setIgnoreDependency(IgnoreDependencyMetaData value);

   /**
    * Gets the value of the aopDomainName property.
    * 
    * @return
    *     possible object is
    *     {@link AopDomainNameType }
    *     
    */
   String getAopDomainName();

   /**
    * Sets the value of the aopDomainName property.
    * 
    * @param value
    *     allowed object is
    *     {@link AopDomainNameType }
    *     
    */
   void setAopDomainName(String value);

   /**
    * Gets the value of the cacheConfig property.
    * 
    * @return
    *     possible object is
    *     {@link CacheConfigMetaData }
    *     
    */
   CacheConfigMetaData getCacheConfig();

   /**
    * Sets the value of the cacheConfig property.
    * 
    * @param value
    *     allowed object is
    *     {@link CacheConfigMetaData }
    *     
    */
   void setCacheConfig(CacheConfigMetaData value);

   /**
    * Gets the value of the poolConfig property.
    * 
    * @return
    *     possible object is
    *     {@link PoolConfigMetaData }
    *     
    */
   PoolConfigMetaData getPoolConfig();

   /**
    * Sets the value of the poolConfig property.
    * 
    * @param value
    *     allowed object is
    *     {@link PoolConfigMetaData }
    *     
    */
   void setPoolConfig(PoolConfigMetaData value);

   /**
    * Gets the value of the concurrent property.
    * 
    * @return
    *     possible object is
    *     {@link ConcurrentType }
    *     
    */
   boolean getConcurrent();

   /**
    * Sets the value of the concurrent property.
    * 
    * @param value
    *     allowed object is
    *     {@link ConcurrentType }
    *     
    */
   void setConcurrent(boolean value);

   /**
    * Gets the value of the jndiRef property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the jndiRef property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getJndiRef().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link JndiRefMetaData }
    * 
    * 
    */
   List<JndiRefMetaData> getJndiRef();

   /**
    * Gets the value of the portComponent property.
    * 
    * @return
    *     possible object is
    *     {@link PortComponentMetaData }
    *     
    */
   PortComponentMetaData getPortComponent();

   /**
    * Sets the value of the portComponent property.
    * 
    * @param value
    *     allowed object is
    *     {@link PortComponentMetaData }
    *     
    */
   void setPortComponent(PortComponentMetaData value);

   /**
    * Gets the value of the ejbTimeoutIdentity property.
    * 
    * @return
    *     possible object is
    *     {@link JBossSecurityIdentityMetaData }
    *     
    */
   JBossSecurityIdentityMetaData getEjbTimeoutIdentity();

   /**
    * Sets the value of the ejbTimeoutIdentity property.
    * 
    * @param value
    *     allowed object is
    *     {@link JBossSecurityIdentityMetaData }
    *     
    */
   void setEjbTimeoutIdentity(JBossSecurityIdentityMetaData value);

}
