//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.06.08 at 07:12:16 PM IST
//

package org.jboss.ejb3.metadata.spi.jboss;

import org.jboss.ejb3.metadata.spi.javaee.PersistenceUnitRefMetaData;

/**
 * <p>Java class for persistence-unit-refType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="persistence-unit-refType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://java.sun.com/xml/ns/javaee}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="persistence-unit-ref-name" type="{http://java.sun.com/xml/ns/javaee}jndi-nameType"/>
 *         &lt;element name="persistence-unit-name" type="{http://java.sun.com/xml/ns/javaee}string" minOccurs="0"/>
 *         &lt;group ref="{http://www.jboss.com/xml/ns/javaee}resourceGroup"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
public interface JBossPersistenceUnitRefMetaData extends PersistenceUnitRefMetaData
{

   /**
    * Gets the value of the jndiName property.
    *
    * @return
    *     possible object is
    *     {@link JndiNameType }
    *
    */
   String getJndiName();

   /**
    * Sets the value of the jndiName property.
    *
    * @param value
    *     allowed object is
    *     {@link JndiNameType }
    *
    */
   void setJndiName(String value);

   /**
    * Gets the value of the ignoreDependency property.
    *
    * @return
    *     possible object is
    *     {@link EmptyType }
    *
    */
   boolean isIgnoreDependency();

   /**
    * Sets the value of the ignoreDependency property.
    *
    * @param value
    *     allowed object is
    *     {@link EmptyType }
    *
    */
   void setIgnoreDependency(boolean value);

}
