//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

import java.util.List;

import org.jboss.ejb3.metadata.spi.javaee.AssemblyDescriptorMetaData;
import org.jboss.ejb3.metadata.spi.javaee.DescriptionMetaData;
import org.jboss.ejb3.metadata.spi.javaee.DisplayNameMetaData;
import org.jboss.ejb3.metadata.spi.javaee.EnterpriseBeanMetaData;
import org.jboss.ejb3.metadata.spi.javaee.IconType;
import org.jboss.ejb3.metadata.spi.javaee.IdMetaData;

/**
 *  The jboss element is the root element of the jboss.xml file. It contains
 *             all the information used by jboss but not described in the ejb-jar.xml file. All of it is
 *             optional. 1- the application assembler can define custom container configurations for the
 *             beans. Standard configurations are provided in standardjboss.xml 2- the deployer can
 *             override the jndi names under which the beans are deployed 3- the deployer can specify
 *             runtime jndi names for resource managers. 
 * 
 * <p>Java class for jbossType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jbossType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.jboss.com/xml/ns/javaee}descriptionGroup"/>
 *         &lt;element name="loader-repository" type="{http://www.jboss.com/xml/ns/javaee}loader-repositoryType" minOccurs="0"/>
 *         &lt;element name="jmx-name" type="{http://www.jboss.com/xml/ns/javaee}jmx-nameType" minOccurs="0"/>
 *         &lt;element name="security-domain" type="{http://www.jboss.com/xml/ns/javaee}security-domainType" minOccurs="0"/>
 *         &lt;element name="missing-method-permissions-excluded-mode" type="{http://www.jboss.com/xml/ns/javaee}missing-method-permissions-excluded-modeType" minOccurs="0"/>
 *         &lt;element name="unauthenticated-principal" type="{http://www.jboss.com/xml/ns/javaee}unauthenticated-principalType" minOccurs="0"/>
 *         &lt;element name="jndi-binding-policy" type="{http://www.jboss.com/xml/ns/javaee}jndi-binding-policyType" minOccurs="0"/>
 *         &lt;element name="jacc-context-id" type="{http://www.jboss.com/xml/ns/javaee}jacc-context-idType" minOccurs="0"/>
 *         &lt;element name="webservices" type="{http://www.jboss.com/xml/ns/javaee}webservicesType" minOccurs="0"/>
 *         &lt;element name="enterprise-beans" type="{http://www.jboss.com/xml/ns/javaee}enterprise-beansType" minOccurs="0"/>
 *         &lt;element name="assembly-descriptor" type="{http://www.jboss.com/xml/ns/javaee}assembly-descriptorType" minOccurs="0"/>
 *         &lt;element name="resource-managers" type="{http://www.jboss.com/xml/ns/javaee}resource-managersType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://java.sun.com/xml/ns/javaee}dewey-versionType" fixed="5.1" />
 *       &lt;attribute name="metadata-complete" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface JBossMetaData extends IdMetaData
{

   /**
    * Gets the value of the description property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the description property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getDescription().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link DescriptionMetaData }
    * 
    * 
    */
   List<DescriptionMetaData> getDescription();

   /**
    * Gets the value of the displayName property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the displayName property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getDisplayName().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link DisplayNameMetaData }
    * 
    * 
    */
   List<DisplayNameMetaData> getDisplayName();

   /**
    * Gets the value of the icon property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the icon property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getIcon().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link IconType }
    * 
    * 
    */
   List<IconType> getIcon();

   /**
    * @return Returns the {@link LoaderRepositoryMetaData}
    *     
    */
   LoaderRepositoryMetaData getLoaderRepository();

   /**
    * Sets the loader repository metadata
    * 
    * @param loaderRepository 
    *     
    */
   void setLoaderRepository(LoaderRepositoryMetaData loaderRepository);

   /**
    * @return Returns the JMX ObjectName of the MBean associated with the ejb-jar module. 
    *     
    */
   String getJmxName();

   /**
    * Sets the JMX ObjectName to use for the MBean associated with the ejb-jar module.
    * This must be a unique name and valid JMX ObjectName string. 
    * 
    * @param jmxName
    */
   void setJmxName(String value);

   /**
    * @return Returns the security domain associated with this ejb module
    *     
    */
   String getSecurityDomain();

   /**
    * Sets the security domain associated with this ejb module
    * 
    * @param securityDomain 
    *     
    */
   void setSecurityDomain(String securityDomain);

   /**
    * The missing-method-permissions-excluded-mode determines the treatment
    *        of missing method-permission mappings in the ejb-jar descriptor. The ejb 2.1
    *        spec states: "It is possible that some methods are not assigned to any security
    *        roles nor contained in the exclude-list element. In this case, it is the
    *        responsibility of the Deployer to assign method permissions for all of the
    *        unspecified methods, either by assigning them to security roles, or by marking
    *        them as unchecked." The missing-method-permissions-excluded-mode is a boolean
    *        that allows the deployer to globally indicate that all methods without a
    *        method-permission element should be treated as excluded(= true and the default),
    *       or that methods without a method-permission element should be treated as
    *        unchecked(= false)
    * 
    * @return Returns true if missing-method-permissions-excluded-mode is set. Else returns false.
    *     
    */
   boolean getMissingMethodPermissionsExcludedMode();

   /**
    * Sets missing-method-permissions-excluded-mode.
    * 
    * @param missingMethodPermissionExcludedMode true if missing-method-permissions-excluded-mode 
    *   is to be set. Else false.
    *   
    *  @see #getMissingMethodPermissionsExcludedMode()
    *     
    */
   void setMissingMethodPermissionsExcludedMode(boolean missingMethodPermissionExcludedMode);

   /**
    * @return Returns the unauthenticated-principal element specifies the name of the principal
    * that will be returned by the EJBContext.getCallerPrincipal() method if there is no
    * authenticated user. This Principal has no roles or privaledges to call any other beans.
    *     
    */
   String getUnauthenticatedPrincipal();

   /**
    * Sets the unauthenticated-principal. See {@link #getUnauthenticatedPrincipal()} for 
    * more details about unauthenticated-principal
    * 
    * @param unauthenticatedPrincipal
    *     
    *     @see #getUnauthenticatedPrincipal()
    *     
    */
   void setUnauthenticatedPrincipal(String unauthenticatedPrincipal);

   /**
    * @return Return the fully qualified class name of the jndi binding policy
    * for this ejb module
    *     
    */
   String getJndiBindingPolicy();

   /**
    * Sets the jndi binding policy of this ejb module
    * 
    * @param jndiBindingPolicy The fully qualified class name of the jndi binding policy
    *     
    */
   void setJndiBindingPolicy(String jndiBindingPolicy);

   /**
    * @return Returns the Jacc context id of this ejb module
    *     
    */
   String getJaccContextId();

   /**
    * Sets the Jacc context id of this ejb module
    * 
    * @param jaccContextId
    *     
    */
   void setJaccContextId(String jaccContextId);

   /**
    * @return Returns the web services metadata in this ejb module
    *     
    */
   WebservicesMetaData getWebservices();

   /**
    * Sets the web services metadata 
    * 
    * @param webServicesMetadata
    *     
    */
   void setWebservices(WebservicesMetaData webServicesMetadata);

   /**
    * @return Returns the enterprise beans present in this ejb module    
    */
   List<EnterpriseBeanMetaData> getEnterpriseBeans();
   
   /**
    * Sets the enterprise beans in this ejb module
    * 
    * @param enterpriseBeans
    */
   void setEnterpriseBeans(List<EnterpriseBeanMetaData> enterpriseBeans);

   /**
    * @return Returns the assembly-descriptor associated with this ejb module
    * 
    */
   AssemblyDescriptorMetaData getAssemblyDescriptor();

   /**
    * Sets the assembly-descriptor in this ejb-module
    * 
    * @param assemblyDescriptor
    *     
    */
   void setAssemblyDescriptor(AssemblyDescriptorMetaData assemblyDescriptor);

   /**
    * @return Returns the resource managers present in this ejb module
    *     
    */
   List<ResourceManagerMetaData> getResourceManagers();

   /**
    * Sets the resource managers in this ejb module
    * 
    * @param resourceManagers 
    */
   void setResourceManagers(List<ResourceManagerMetaData> resourceManagers);

   /**
    * @return Returns true if this ejb module is marked as metadata complete.
    * Else returns false.
    */
   boolean isMetadataComplete();

   /**
    * Set to true if the ejb module is metadata complete. Else set to false
    * 
    * @param isMetadataComplete
    */
   void setMetadataComplete(Boolean isMetadataComplete);

}
