//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

import java.io.Serializable;
import java.util.List;
import javax.xml.bind.JAXBElement;

/**
 * 
 *             
 *       The loader-repository specifies the name of the UnifiedLoaderRepository
 *    MBean to use for the ear to provide ear level scoping of classes deployed
 *    in the ear. It is a unique JMX ObjectName string. It may also specify
 *    an arbitrary configuration by including a loader-repository-config element.
 * 
 * Examples:
 *    <loader-repository>jboss.test:loader=cts-cmp2v1-sar.ear</loader-repository>
 * 
 *    <loader-repository loaderRepositoryClass='dot.com.LoaderRepository'>
 *       dot.com:loader=unique-archive-name
 *       <loader-repository-config configParserClass='dot.com.LoaderParser'>
 *          java2ParentDelegaton=true
 *       </loader-repository-config>
 *    </loader-repository>
 *         </loader-repository>
 *         
 *          
 * 
 * <p>Java class for loader-repositoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="loader-repositoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="loader-repository-config" type="{http://www.jboss.com/xml/ns/javaee}loader-repository-configType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="loaderRepositoryClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface LoaderRepositoryMetaData
{

   /**
    * 
    *             
    *       The loader-repository specifies the name of the UnifiedLoaderRepository
    *    MBean to use for the ear to provide ear level scoping of classes deployed
    *    in the ear. It is a unique JMX ObjectName string. It may also specify
    *    an arbitrary configuration by including a loader-repository-config element.
    * 
    * Examples:
    *    <loader-repository>jboss.test:loader=cts-cmp2v1-sar.ear</loader-repository>
    * 
    *    <loader-repository loaderRepositoryClass='dot.com.LoaderRepository'>
    *       dot.com:loader=unique-archive-name
    *       <loader-repository-config configParserClass='dot.com.LoaderParser'>
    *          java2ParentDelegaton=true
    *       </loader-repository-config>
    *    </loader-repository>
    *         </loader-repository>
    *         
    *          Gets the value of the content property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the content property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getContent().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link String }
    * {@link JAXBElement }{@code <}{@link LoaderRepositoryConfigMetaData }{@code >}
    * 
    * 
    */
   List<Serializable> getContent();

   /**
    * Gets the value of the id property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getId();

   /**
    * Sets the value of the id property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setId(String value);

   /**
    * Gets the value of the loaderRepositoryClass property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getLoaderRepositoryClass();

   /**
    * Sets the value of the loaderRepositoryClass property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setLoaderRepositoryClass(String value);

}
