//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

/**
 *  The method element is used to specify attributes for one method or all
 *             those matching a pattern startingstring*. 
 * 
 * <p>Java class for methodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="methodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="method-name" type="{http://java.sun.com/xml/ns/javaee}method-nameType"/>
 *         &lt;element name="read-only" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="idempotent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="transaction-timeout" type="{http://www.jboss.com/xml/ns/javaee}transaction-timeoutType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface MethodMetaData
{

   /**
    * Gets the value of the methodName property.
    * 
    * @return
    *     possible object is
    *     {@link MethodNameType }
    *     
    */
   String getMethodName();

   /**
    * Sets the value of the methodName property.
    * 
    * @param value
    *     allowed object is
    *     {@link MethodNameType }
    *     
    */
   void setMethodName(String value);

   /**
    * Gets the value of the readOnly property.
    * 
    * @return
    *     possible object is
    *     {@link Boolean }
    *     
    */
   Boolean isReadOnly();

   /**
    * Sets the value of the readOnly property.
    * 
    * @param value
    *     allowed object is
    *     {@link Boolean }
    *     
    */
   void setReadOnly(Boolean value);

   /**
    * Gets the value of the idempotent property.
    * 
    * @return
    *     possible object is
    *     {@link Boolean }
    *     
    */
   Boolean isIdempotent();

   /**
    * Sets the value of the idempotent property.
    * 
    * @param value
    *     allowed object is
    *     {@link Boolean }
    *     
    */
   void setIdempotent(Boolean value);

   /**
    * Gets the value of the transactionTimeout property.
    * 
    * @return
    *     possible object is
    *     {@link TransactionTimeoutType }
    *     
    */
   String getTransactionTimeout();

   /**
    * Sets the value of the transactionTimeout property.
    * 
    * @param value
    *     allowed object is
    *     {@link TransactionTimeoutType }
    *     
    */
   void setTransactionTimeout(String value);

   /**
    * Gets the value of the id property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getId();

   /**
    * Sets the value of the id property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setId(String value);

}
