//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.06.08 at 07:12:16 PM IST
//

package org.jboss.ejb3.metadata.spi.jboss;

/**
 * Element for specifying the pool configuration of a bean
 *
 * <p>Java class for pool-configType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="pool-configType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pool-value" type="{http://www.jboss.com/xml/ns/javaee}pool-valueType" minOccurs="0"/>
 *         &lt;element name="pool-max-size" type="{http://www.jboss.com/xml/ns/javaee}pool-max-sizeType" minOccurs="0"/>
 *         &lt;element name="pool-timeout" type="{http://www.jboss.com/xml/ns/javaee}pool-timeoutType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
public interface PoolConfigMetaData
{

   /**
    *
    * @return Returns the pool type
    *
    */
   String getPoolValue();

   /**
    * Sets the pool type
    *
    * @param poolValue
    *
    */
   void setPoolValue(String poolValue);

   /**
    *
    * @return Returns the max size of the pool
    *
    */
   long getPoolMaxSize();

   /**
    * Sets the max size of the pool
    *
    * @param maxSize Max size of the pool
    *
    */
   void setPoolMaxSize(long maxSize);

   /**
    *
    * @return Returns the number of seconds before an pool thread times out
    *
    */
   long getPoolTimeout();

   /**
    * Sets the number of seconds before an pool thread times out
    *
    * @param poolTimeoutInSeconds Number of seconds before a pool thread times out
    *
    */
   void setPoolTimeout(long poolTimeoutInSeconds);

}
