//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

import java.util.List;

/**
 * <p>Java class for port-component-refType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="port-component-refType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="service-endpoint-interface" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="port-qname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="config-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="config-file" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stub-property" type="{http://www.jboss.com/xml/ns/javaee}stub-propertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="call-property" type="{http://www.jboss.com/xml/ns/javaee}call-propertyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface PortComponentRefMetaData
{

   /**
    * Gets the value of the serviceEndpointInterface property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getServiceEndpointInterface();

   /**
    * Sets the value of the serviceEndpointInterface property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setServiceEndpointInterface(String value);

   /**
    * Gets the value of the portQname property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getPortQname();

   /**
    * Sets the value of the portQname property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setPortQname(String value);

   /**
    * Gets the value of the configName property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getConfigName();

   /**
    * Sets the value of the configName property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setConfigName(String value);

   /**
    * Gets the value of the configFile property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getConfigFile();

   /**
    * Sets the value of the configFile property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setConfigFile(String value);

   /**
    * Gets the value of the stubProperty property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the stubProperty property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getStubProperty().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link StubPropertyMetaData }
    * 
    * 
    */
   List<StubPropertyMetaData> getStubProperty();

   /**
    * Gets the value of the callProperty property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the callProperty property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getCallProperty().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link CallPropertyMetaData }
    * 
    * 
    */
   List<CallPropertyMetaData> getCallProperty();

}
