//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.06.08 at 07:12:16 PM IST
//

package org.jboss.ejb3.metadata.spi.jboss;

import org.jboss.ejb3.metadata.spi.javaee.IdMetaData;

/**
 *
 *
 *          The port-component element specifies a mapping from a webservice
 *          port-component whose service-impl-bean/ejb-link value maps to an ejb.
 *          Used in: session
 *
 *
 *
 *
 * <p>Java class for port-componentType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="port-componentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="port-component-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="port-component-uri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="auth-method" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transport-guarantee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="secure-wsdl-access" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
public interface PortComponentMetaData extends IdMetaData
{

   /**
    *
    * @return Returns the port component name
    *
    */
   String getPortComponentName();

   /**
    * Sets the port component name
    *
    * @param portComponentName The port component name
    *
    */
   void setPortComponentName(String portComponentName);

   /**
    *
    * @return Returns the port component URI
    *
    */
   String getPortComponentUri();

   /**
    * Sets the port component uri
    *
    * @param portComponentURI
    *
    */
   void setPortComponentUri(String value);

   /**
    *
    * @return Returns the auth method
    *
    */
   String getAuthMethod();

   /**
    * Sets the auth method
    *
    * @param authMethod
    *
    */
   void setAuthMethod(String authMethod);

   /**
    *
    * @return Returns the transport guarantee
    *
    */
   String getTransportGuarantee();

   /**
    * Sets the transport guaranteee
    *
    * @param transportGuarantee
    *
    */
   void setTransportGuarantee(String transportGuarantee);

   /**
    * @return Returns true if the port component is set for secure wsdl access.
    * Else returns false
    *
    */
   boolean isSecureWsdlAccess();

   /**
    * Set true if the port component is to be set for secure wsdl access.
    * Else set to false
    *
    * @param isSecureWsdlAccess True if the port component is to be set for secure wsdl access.
    * Else set to false
    *
    */
   void setSecureWsdlAccess(boolean isSecureWsdlAccess);


}
