//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

/**
 * 
 *             
 *          The port-component element specifies a mapping from a webservice
 *          port-component whose service-impl-bean/ejb-link value maps to an ejb.
 *          Used in: session
 * 
 *             
 *          
 * 
 * <p>Java class for port-componentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="port-componentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="port-component-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="port-component-uri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="auth-method" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transport-guarantee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="secure-wsdl-access" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface PortComponentMetaData
{

   /**
    * Gets the value of the portComponentName property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getPortComponentName();

   /**
    * Sets the value of the portComponentName property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setPortComponentName(String value);

   /**
    * Gets the value of the portComponentUri property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getPortComponentUri();

   /**
    * Sets the value of the portComponentUri property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setPortComponentUri(String value);

   /**
    * Gets the value of the authMethod property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getAuthMethod();

   /**
    * Sets the value of the authMethod property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setAuthMethod(String value);

   /**
    * Gets the value of the transportGuarantee property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getTransportGuarantee();

   /**
    * Sets the value of the transportGuarantee property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setTransportGuarantee(String value);

   /**
    * Gets the value of the secureWsdlAccess property.
    * 
    * @return
    *     possible object is
    *     {@link Boolean }
    *     
    */
   Boolean isSecureWsdlAccess();

   /**
    * Sets the value of the secureWsdlAccess property.
    * 
    * @param value
    *     allowed object is
    *     {@link Boolean }
    *     
    */
   void setSecureWsdlAccess(Boolean value);

   /**
    * Gets the value of the id property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getId();

   /**
    * Sets the value of the id property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setId(String value);

}
