//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

import java.util.List;

import org.jboss.ejb3.metadata.spi.javaee.DescriptionMetaData;

/**
 *  The resource-managers element is used to declare resource managers. A
 *             resource has 3 names: - the "code name" is the name used in the code of the bean, supplied
 *             by the Bean Developer in the resource-ref section of the ejb-jar.xml file - the "xml name"
 *             is an intermediary name used by the Application Assembler to identify resources in the XML
 *             file. - the "runtime jndi name" is the actual jndi-name or url of the deployed resource, it
 *             is supplied by the Deployer. The mapping between the "code name" and the "xml name" is given
 *             in the resource-ref section for the bean. If not, jboss will assume that "xml name" = "code
 *             name". The mapping between the "xml name" and the "runtime jndi name" is given in a
 *             resource-manager section. If not, and if the datasource is of type javax.sql.DataSource,
 *             jboss will look for a javax.sql.DataSource in the jndi tree. Used in: jboss
 *          
 * 
 * <p>Java class for resource-managersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resource-managersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://java.sun.com/xml/ns/javaee}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="resource-manager" type="{http://www.jboss.com/xml/ns/javaee}resource-managerType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface ResourceManagersMetaData
{

   /**
    * Gets the value of the description property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the description property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getDescription().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link DescriptionMetaData }
    * 
    * 
    */
   List<DescriptionMetaData> getDescription();

   /**
    * @return Returns a list of resource managers
    * 
    * 
    */
   List<ResourceManagerMetaData> getResourceManagers();
   
   /**
    * Sets the resource managers
    * 
    * @param resourceManagers
    */
   void setResourceManagers(List<ResourceManagerMetaData> resourceManagers);

}
