//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

import java.util.List;

/**
 * <p>Java class for webservicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="webservicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="context-root" type="{http://java.sun.com/xml/ns/javaee}string" minOccurs="0"/>
 *         &lt;element name="webservice-description" type="{http://www.jboss.com/xml/ns/javaee}webservice-descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface WebservicesMetaData
{

   /**
    * Gets the value of the contextRoot property.
    * 
    * @return
    *     possible object is
    *     {@link com.sun.java.xml.ns.javaee.String }
    *     
    */
   String getContextRoot();

   /**
    * Sets the value of the contextRoot property.
    * 
    * @param value
    *     allowed object is
    *     {@link com.sun.java.xml.ns.javaee.String }
    *     
    */
   void setContextRoot(String value);

   /**
    * Gets the value of the webserviceDescription property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the webserviceDescription property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getWebserviceDescription().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link WebserviceDescriptionMetaData }
    * 
    * 
    */
   List<WebserviceDescriptionMetaData> getWebserviceDescription();

   /**
    * Gets the value of the id property.
    * 
    * @return
    *     possible object is
    *     {@link java.lang.String }
    *     
    */
   java.lang.String getId();

   /**
    * Sets the value of the id property.
    * 
    * @param value
    *     allowed object is
    *     {@link java.lang.String }
    *     
    */
   void setId(java.lang.String value);

}
