//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

/**
 * 
 *             
 *             Runtime information about a web service.
 *             wsdl-publish-location is optionally used to specify
 *             where the final wsdl and any dependent files should be stored.  This location
 *             resides on the file system from which deployment is initiated.
 *             
 *          
 * 
 * <p>Java class for webservice-descriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="webservice-descriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="webservice-description-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="config-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="config-file" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="wsdl-publish-location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface WebserviceDescriptionMetaData
{

   /**
    * Gets the value of the webserviceDescriptionName property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getWebserviceDescriptionName();

   /**
    * Sets the value of the webserviceDescriptionName property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setWebserviceDescriptionName(String value);

   /**
    * Gets the value of the configName property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getConfigName();

   /**
    * Sets the value of the configName property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setConfigName(String value);

   /**
    * Gets the value of the configFile property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getConfigFile();

   /**
    * Sets the value of the configFile property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setConfigFile(String value);

   /**
    * Gets the value of the wsdlPublishLocation property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getWsdlPublishLocation();

   /**
    * Sets the value of the wsdlPublishLocation property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setWsdlPublishLocation(String value);

   /**
    * Gets the value of the id property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   String getId();

   /**
    * Sets the value of the id property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   void setId(String value);

}
