//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.jboss;

import java.util.List;

import org.jboss.ejb3.metadata.spi.javaee.IdMetaData;

/**
 * <p>Java class for webservicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="webservicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="context-root" type="{http://java.sun.com/xml/ns/javaee}string" minOccurs="0"/>
 *         &lt;element name="webservice-description" type="{http://www.jboss.com/xml/ns/javaee}webservice-descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface WebservicesMetaData extends IdMetaData
{

   /**
    * @return Returns the context root of this webservice
    *     
    */
   String getContextRoot();

   /**
    * Sets the context root of this webservice
    * 
    * @param contextRoot Context root of the webservice
    *     
    */
   void setContextRoot(String contextRoot);

   /**
    * @return Returns the webservice descriptions
    * 
    * 
    */
   List<WebserviceDescriptionMetaData> getWebserviceDescriptions();

   /**
    * Sets the webservice descriptions
    *  
    * @param webserviceDescriptions
    */
   void setWebServiceDescriptions(List<WebserviceDescriptionMetaData> webserviceDescriptions);

}
