//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.javaee;

/**
 * <p>Java class for init-methodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="init-methodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="create-method" type="{http://java.sun.com/xml/ns/javaee}named-methodType"/>
 *         &lt;element name="bean-method" type="{http://java.sun.com/xml/ns/javaee}named-methodType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface InitMethodMetaData
{

   /**
    * Gets the value of the createMethod property.
    * 
    * @return
    *     possible object is
    *     {@link NamedMethodMetaData }
    *     
    */
   NamedMethodMetaData getCreateMethod();

   /**
    * Sets the value of the createMethod property.
    * 
    * @param value
    *     allowed object is
    *     {@link NamedMethodMetaData }
    *     
    */
   void setCreateMethod(NamedMethodMetaData value);

   /**
    * Gets the value of the beanMethod property.
    * 
    * @return
    *     possible object is
    *     {@link NamedMethodMetaData }
    *     
    */
   NamedMethodMetaData getBeanMethod();

   /**
    * Sets the value of the beanMethod property.
    * 
    * @param value
    *     allowed object is
    *     {@link NamedMethodMetaData }
    *     
    */
   void setBeanMethod(NamedMethodMetaData value);

   /**
    * Gets the value of the id property.
    * 
    * @return
    *     possible object is
    *     {@link java.lang.String }
    *     
    */
   java.lang.String getId();

   /**
    * Sets the value of the id property.
    * 
    * @param value
    *     allowed object is
    *     {@link java.lang.String }
    *     
    */
   void setId(java.lang.String value);

}
