//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.javaee;

/**
 * 
 * 
 * 	The port-component-ref element declares a client dependency
 * 	on the container for resolving a Service Endpoint Interface
 * 	to a WSDL port. It optionally associates the Service Endpoint
 * 	Interface with a particular port-component. This is only used
 * 	by the container for a Service.getPort(Class) method call.
 * 
 *       
 * 
 * <p>Java class for port-component-refType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="port-component-refType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="service-endpoint-interface" type="{http://java.sun.com/xml/ns/javaee}fully-qualified-classType"/>
 *         &lt;element name="enable-mtom" type="{http://java.sun.com/xml/ns/javaee}true-falseType" minOccurs="0"/>
 *         &lt;element name="port-component-link" type="{http://java.sun.com/xml/ns/javaee}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface PortComponentRefMetaData
{

   /**
    * Gets the value of the serviceEndpointInterface property.
    * 
    * @return
    *     possible object is
    *     {@link FullyQualifiedClassType }
    *     
    */
   String getServiceEndpointInterface();

   /**
    * Sets the value of the serviceEndpointInterface property.
    * 
    * @param value
    *     allowed object is
    *     {@link FullyQualifiedClassType }
    *     
    */
   void setServiceEndpointInterface(String value);

   /**
    * Gets the value of the enableMtom property.
    * 
    * @return
    *     possible object is
    *     {@link TrueFalseType }
    *     
    */
   boolean getEnableMtom();

   /**
    * Sets the value of the enableMtom property.
    * 
    * @param value
    *     allowed object is
    *     {@link TrueFalseType }
    *     
    */
   void setEnableMtom(boolean value);

   /**
    * Gets the value of the portComponentLink property.
    * 
    * @return
    *     possible object is
    *     {@link com.sun.java.xml.ns.javaee.String }
    *     
    */
   String getPortComponentLink();

   /**
    * Sets the value of the portComponentLink property.
    * 
    * @param value
    *     allowed object is
    *     {@link com.sun.java.xml.ns.javaee.String }
    *     
    */
   void setPortComponentLink(String value);

   /**
    * Gets the value of the id property.
    * 
    * @return
    *     possible object is
    *     {@link java.lang.String }
    *     
    */
   java.lang.String getId();

   /**
    * Sets the value of the id property.
    * 
    * @param value
    *     allowed object is
    *     {@link java.lang.String }
    *     
    */
   void setId(java.lang.String value);

}
