//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.javaee;

/**
 * 
 * 
 * 	The queryType defines a finder or select
 * 	query. It contains
 * 	    - an optional description of the query
 * 	    - the specification of the finder or select
 * 	      method it is used by
 * 		- an optional specification of the result type
 * 		  mapping, if the query is for a select method
 * 		  and entity objects are returned.
 * 		- the EJB QL query string that defines the query.
 * 
 * 	Queries that are expressible in EJB QL must use the ejb-ql
 * 	element to specify the query. If a query is not expressible
 * 	in EJB QL, the description element should be used to
 * 	describe the semantics of the query and the ejb-ql element
 * 	should be empty.
 * 
 * 	The result-type-mapping is an optional element. It can only
 * 	be present if the query-method specifies a select method
 * 	that returns entity objects.  The default value for the
 * 	result-type-mapping element is "Local".
 * 
 *       
 * 
 * <p>Java class for queryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://java.sun.com/xml/ns/javaee}descriptionType" minOccurs="0"/>
 *         &lt;element name="query-method" type="{http://java.sun.com/xml/ns/javaee}query-methodType"/>
 *         &lt;element name="result-type-mapping" type="{http://java.sun.com/xml/ns/javaee}result-type-mappingType" minOccurs="0"/>
 *         &lt;element name="ejb-ql" type="{http://java.sun.com/xml/ns/javaee}xsdStringType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface QueryMetaData extends IdMetaData
{

   /**
    * Gets the value of the description property.
    * 
    * @return
    *     possible object is
    *     {@link DescriptionMetaData }
    *     
    */
   DescriptionMetaData getDescription();

   /**
    * Sets the value of the description property.
    * 
    * @param value
    *     allowed object is
    *     {@link DescriptionMetaData }
    *     
    */
   void setDescription(DescriptionMetaData value);

   /**
    * Gets the value of the queryMethod property.
    * 
    * @return
    *     possible object is
    *     {@link QueryMethodMetaData }
    *     
    */
   NamedMethodMetaData getQueryMethod();

   /**
    * Sets the value of the queryMethod property.
    * 
    * @param value
    *     allowed object is
    *     {@link QueryMethodMetaData }
    *     
    */
   void setQueryMethod(NamedMethodMetaData value);

   /**
    * Returns the result-type-mapping
    * 
    * The result-type-mappingType is used in the query element to
    * specify whether an abstract schema type returned by a query
    * for a select method is to be mapped to an EJBLocalObject or
    * EJBObject type.
    *     
    */
   ResultTypeMappingType getResultTypeMapping();

   /**
    * Sets the result-type-mapping type
    * 
    * @param resultTypeMapping
    *     
    */
   void setResultTypeMapping(ResultTypeMappingType resultTypeMapping);

   /**
    * Returns the ejb-ql query.
    *     
    */
   String getEjbQl();

   /**
    * Sets the ejb-ql query
    * 
    * @param query
    *     
    */
   void setEjbQl(String query);

}
