//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.06.08 at 07:12:16 PM IST
//

package org.jboss.ejb3.metadata.spi.javaee;

import java.util.List;

/**
 *
 *
 * 	The security-identityType specifies whether the caller's
 * 	security identity is to be used for the execution of the
 * 	methods of the enterprise bean or whether a specific run-as
 * 	identity is to be used. It contains an optional description
 * 	and a specification of the security identity to be used.
 *
 *
 *
 * <p>Java class for security-identityType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="security-identityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://java.sun.com/xml/ns/javaee}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="use-caller-identity" type="{http://java.sun.com/xml/ns/javaee}emptyType"/>
 *           &lt;element name="run-as" type="{http://java.sun.com/xml/ns/javaee}run-asType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
public interface SecurityIdentityMetaData
{

   /**
    * Gets the value of the description property.
    *
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the description property.
    *
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getDescription().add(newItem);
    * </pre>
    *
    *
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link DescriptionMetaData }
    *
    *
    */
   List<DescriptionMetaData> getDescription();

   /**
    * Gets the value of the useCallerIdentity property.
    *
    * @return
    *     possible object is
    *     {@link EmptyType }
    *
    */
   boolean isUseCallerIdentity();

   /**
    * Sets the value of the useCallerIdentity property.
    *
    * @param value
    *     allowed object is
    *     {@link EmptyType }
    *
    */
   void setUseCallerIdentity(boolean value);

   /**
    * Gets the value of the runAs property.
    *
    * @return
    *     possible object is
    *     {@link RunAsMetaData }
    *
    */
   RunAsMetaData getRunAs();

   /**
    * Sets the value of the runAs property.
    *
    * @param value
    *     allowed object is
    *     {@link RunAsMetaData }
    *
    */
   void setRunAs(RunAsMetaData value);

   /**
    * Gets the value of the id property.
    *
    * @return
    *     possible object is
    *     {@link java.lang.String }
    *
    */
   java.lang.String getId();

   /**
    * Sets the value of the id property.
    *
    * @param value
    *     allowed object is
    *     {@link java.lang.String }
    *
    */
   void setId(java.lang.String value);

}
