//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 07:12:16 PM IST 
//

package org.jboss.ejb3.metadata.spi.javaee;

import java.util.List;

/**
 * 
 * 
 *       The handler-chains element defines the handlerchains associated with this
 *       service or service endpoint.
 * 
 *       
 * 
 * <p>Java class for service-ref_handler-chainsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="service-ref_handler-chainsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="handler-chain" type="{http://java.sun.com/xml/ns/javaee}service-ref_handler-chainType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface ServiceRefHandlerChainsMetaData extends IdMetaData
{

   /**
    * @return Returns the service ref handler chains
    * 
    * 
    */
   List<ServiceRefHandlerChainMetaData> getHandlerChains();
   
   /**
    * Sets the service ref handler chains
    * 
    * @param handlerChains
    */
   void setHandlerChains(List<ServiceRefHandlerChainMetaData> handlerChains);

   

}
